### ISSUE TITLE
Facilities Missing from Playground Equipment List

### ISSUE THREAD

**Issue by csmulroy** [andrewviren/PPRstat.accde#128]
Jose Manuel
Konrad
Ralph Brooks
Reyburn
West Fairmount

**Comment by andrewviren** [comment]
Jose Manuel --> request submitted
Konrad --> mislabeled, no playground at this park. Please look for context clues where this should be.
Ralph Brooks --> request submitted
Reyburn --> Cecil B Moore
West Fairmount --> Parkside Evans
