### ISSUE TITLE
Permits are not being captured when printing them out

### ISSUE THREAD

**Issue by mirosado** [andrewviren/PPRstat.accde#19]
Permits 11824 and 11856 did not show up in the print previews.

**Comment by mirosado** [comment]
Permits 11894, 11895, 11918, 11921, 11930, and 11939 did not show up in the print previews.

**Comment by mirosado** [comment]
Permits 11977 and 11979 did not show up in the print previews.

**Comment by mirosado** [comment]
Reprinted Permits 11800-11968. 11930 and 11895 did not show up in print previews again (Others, however, did appear in print preview).

**Comment by mirosado** [comment]
Permit 12030 did not show up in the print previews.

**Comment by mirosado** [comment]
Permits 12073-12075, 12090, and 12095 did not show up in the print previews.

**Comment by mirosado** [comment]
Permit 12192 did not show up in the print previews.

**Comment by mirosado** [comment]
Permits 12214, 12235, 12298, 12299 did not show up in the print previews.

**Comment by mirosado** [comment]
Permits 12343, 12344, 12368, 12408, 12425, 12433, 12457, 12460, 12462, 12473, 12475 did not show up in the print previews.

**Comment by mirosado** [comment]
Permits 12577 and 12578 did not show up in the print previews.

**Comment by mirosado** [comment]
Permits 12739 and 12748 did not show up in the print previews.

**Comment by mirosado** [comment]
Permit 12776 did not show up in the print previews.

**Comment by mirosado** [comment]
Permits 12872, 12875, 12877, 12879 did not show up in the print previews. (Noticed all of these permits were for use on a single day.)

**Comment by mirosado** [comment]
Permits 12932, 12933, 12935, 12936, and 12938 did not show up in the print previews.

**Comment by mirosado** [comment]
Permit 12981 did not show up in the print previews.

**Comment by mirosado** [comment]
Permits  13021, 13022, 13023, 13030, 13037, 13043  did not show up in the print previews

**Comment by mirosado** [comment]
Permits 13079, 13088, 13090, 13091, 13094, 13101 did not show up in the print previews. 13094 did print at first, but when an extra amenity was removed, stop showing in print preview.

**Comment by mirosado** [comment]
Permit 13228 did not show up in the print previews. (Schedule already occured)

**Comment by mirosado** [comment]
Permits 13340,  13342, and 13343 did not show up in the print previews.

**Comment by tomchaykun** [comment]
Permits 13472 and 13475 did not show up in the print previews (Schedule already occurred)

**Comment by mirosado** [comment]
Permits 133543, 13545, 13585, and 13590 did not show up in the print previews (first 3 already occurred).

**Comment by tomchaykun** [comment]
Permits 13679 and 13682 did not show up in print previews. 13679 was first entered for week and 13682 already occurred.
