### ISSUE TITLE
Add to PPR Stat (Staff Approver)

### ISSUE THREAD

**Issue by mirosado** [andrewviren/PPRstat.accde#26]
Add Peter Kurtz to list of Staff Approvers.

**Comment by mirosado** [comment]
Please add Jeff Wimsey to list of Staff Approvers as well.

**Comment by mirosado** [comment]
Please add Kimberly Jones Kendall to list of Staff Approvers.

**Comment by mirosado** [comment]
Please add Brett Bessler to the list of Staff Aprrovers.

**Comment by mirosado** [comment]
Please add Jameele Mitchell to the list of Staff Aprrovers.

**Comment by mirosado** [comment]
Edit: Listed under Betsy, not Elizabeth. 
Please add Elizabeth Henninger to the list of Staff Approvers.

**Comment by mirosado** [comment]
Please add Greg Harling to the list of Staff Approvers.

**Comment by mirosado** [comment]
Please add Zainab J. Abdur Rahman to the list of Staff Approvers.

**Comment by mirosado** [comment]
Please add Greg Frangipani to the list of Staff Approvers.

**Comment by mirosado** [comment]
Please add Jamilla Abdur-Rahman to the list of Staff Approvers.

**Comment by mirosado** [comment]
Please add Kevin Regan to the list of Staff Approvers.

**Comment by tomchaykun** [comment]
Please add Emily Coleman to list of Staff Aprovers.

**Comment by tomchaykun** [comment]
Please add Jameele (?) Mitchell to list of Staff Approvers. Not sure about spelling. Listed on Wister AAP 13691, 20170907.
